[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.flash_mode = dio
board_build.merge_bin = true
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    https://github.com/SanteriLindfors/WiFiProvisioner.git
    ArduinoJson
build_flags =
    -DCORE_DEBUG_LEVEL=1
